### ISSUE TITLE
FEW MINOR CHANGES

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#1]
1.For HOUSING OD,HEAD AND BASE OD  default should be in capital letters as DEFAULT
2.FOR RETROFITTING SLB/REDA IS NOT COMING IN SAME LINE 
3.IN THE SUMMARY SCREEN FOR TYPE OF FLOW IT IS MIXED THAT MIXED SHOULD BE IN CAPITAL LETTERS
![NE1](https://user-images.githubusercontent.com/53165464/64148376-cb90bd00-ce40-11e9-99bd-11317a718ee7.PNG)
![NE2](https://user-images.githubusercontent.com/53165464/64148386-d1869e00-ce40-11e9-82ea-33c9ab64f563.PNG)
![NE3](https://user-images.githubusercontent.com/53165464/64148391-d6e3e880-ce40-11e9-9699-7f2c6dd10001.PNG)

![NE5](https://user-images.githubusercontent.com/53165464/64148397-db100600-ce40-11e9-8759-c41047859b18.PNG)

**Comment by questglobal-bom** [comment]
Please raise different bugs for all the mentioned issues.
