### ISSUE TITLE
PROPER ALIGNMENT IN DISPLAY OF HOUSING MATERIAL OF AR SCREEN

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#10]
1.IT IS DISPLAYED AS HOUSING MATERIAL =13CR STAINL
SHOULD BE DISPLAYED AS 13CR STAINLESS STEEL
2.SIMILARLY FOR HEAD AND BASE MATERIAL ALSO ALIGNMENT IS NOT PROPER
![NE13](https://user-images.githubusercontent.com/53165464/64171190-a9fafa00-ce6f-11e9-8da1-2b75ae27a1dc.PNG)

![NE12](https://user-images.githubusercontent.com/53165464/64170984-16292e00-ce6f-11e9-87db-adff98d814a3.PNG)

**Comment by kumatolemahesh** [comment]
Fixed
