### ISSUE TITLE
In generate PART ATTRIBUTE the following description is showing error

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#105]
![image](https://user-images.githubusercontent.com/53165464/75319994-b9458800-5893-11ea-9707-c61759f703f3.png)
![image](https://user-images.githubusercontent.com/53165464/75320079-f27df800-5893-11ea-96fd-f82475ac21af.png)

**Comment by questglobal-bom** [comment]
Fixed.

**Comment by prathika123** [comment]
working
