### ISSUE TITLE
FOR SF350 BEARING RATIO IS NOT REFLECTING IMMEDIATELY

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#12]
WHEN DEFAULT  SELECTING SF=SF350
IT SHOWS EMPTY IN BEARING RATIO
AFTER SELECTING SF= SF500 OR SOMEOTHER STAGEFLOW 
THEN IT IS REFLECTING VALUES FOR SF350
![NE14](https://user-images.githubusercontent.com/53165464/64173466-fd237b80-ce74-11e9-8030-673aa9efa3e5.PNG)
![NE15](https://user-images.githubusercontent.com/53165464/64173477-0280c600-ce75-11e9-9889-93a7fb66fab3.PNG)
![NE16](https://user-images.githubusercontent.com/53165464/64173487-0876a700-ce75-11e9-9ad0-2ba12505d0e9.PNG)

**Comment by prathika123** [comment]
SIMILARLY FOR EVERY DEFAULT SF STARTING VALUES IT IS NOT REFLECTING

**Comment by kumatolemahesh** [comment]
FIXED
