### ISSUE TITLE
HOUSING MATERIAL OF EVERY SCREEN SHOULD DISPLAY 9 CR STAINLESS STEEL INSTEAD OF STAINLESS STEEL 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#15]
IT IS DISPLAYED AS STAINLESS STEEL BUT IT SHOULD DISPLAY AS 9 CR STAINLESS STEEL IN EVERY FLOATER ,  AR , COMPRESSION SCREENS
![NE18](https://user-images.githubusercontent.com/53165464/64234328-ba64b080-cf13-11e9-8805-e5bf716dd9a7.PNG)
![NE17](https://user-images.githubusercontent.com/53165464/64234338-c0f32800-cf13-11e9-915e-ad37ec8b5aa3.PNG)

**Comment by kumatolemahesh** [comment]
FIXED
