### ISSUE TITLE
THIRD SCREEN OF AR/GR COMPRESSION SHOULD BE CHANGED 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#17]
3RD SCREEN SHOULD BE 
![NE19](https://user-images.githubusercontent.com/53165464/64236604-5bee0100-cf18-11e9-875d-caef5d6816b0.PNG)
![NE20](https://user-images.githubusercontent.com/53165464/64236616-614b4b80-cf18-11e9-96fe-f836020b0a55.PNG)

STAGEFLOW,BEARING RATIOS
4TH SCREEN SHOULD BE O-RING MATERIAL,CLOCKING,COATING

IT IS DISPLAYING REVERSE

**Comment by kumatolemahesh** [comment]
FIXED
