### ISSUE TITLE
BEARING RATIOS ARE NOT REFLECTING IMMEDIATELY IN AR/GR SCREEN 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#18]
FOR EX:IF SF IS BY DEFAULT 350 IT DOESN'T SHOW BEARING RATIOS IMMEDIATELY,WHEN SF IS SELECTED AS SF500 THEN IT IS REFLECTING FOR SF350 NOT ONLY FOR SF350 FOR EVERY DEFAULT STAGEFLOWS PRESENT AFTER SELECTING SERIES IS SHOWING SAME ERROR

**Comment by kumatolemahesh** [comment]
when user selects stage flow, bearing ratios will be populated automatically
