### ISSUE TITLE
pdf and excel generating make-up sleeve 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#19]
ACCORDING TO GIVEN INPUTS 
![NE22](https://user-images.githubusercontent.com/53165464/64247271-1cc9ab00-cf2c-11e9-83a5-25fa23fb17ea.PNG)
THE OUTPUT SHOULD BE 
![NE23](https://user-images.githubusercontent.com/53165464/64247287-294e0380-cf2c-11e9-87d8-eea8885e3786.PNG)
BUT THE OUTPUT IS 
![ne21](https://user-images.githubusercontent.com/53165464/64247312-34089880-cf2c-11e9-9e7a-878d8730540a.PNG)
AS FROM THE CALCULATIONS I COULD SEE THE MAKEUP SLEEVE VALUE 
MAKEUP SLEEVE=NO.OF REGULAR IMPELLER BUT IT SHOULD NOT BE PRESENT

**Comment by questglobal-bom** [comment]
Fixed.
