### ISSUE TITLE
MINOR CHANGES TO BE UPDATED IN UI

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#2]
1. FOR HOUSING OD AND HEAD AND BASE OD Default should be in capital letters as DEFAULT

![NE1](https://user-images.githubusercontent.com/53165464/64148821-efa0ce00-ce41-11e9-965c-37cf0a223bfd.PNG)
![NE3](https://user-images.githubusercontent.com/53165464/64148829-f596af00-ce41-11e9-80d0-d2a208799fdd.PNG)

**Comment by questglobal-bom** [comment]
Fixed.
