### ISSUE TITLE
EMPTY ROWS ARE COMING IN PDF AND EXCEL SHEET

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#20]
ACTUAL RESULT  IS
![NE25](https://user-images.githubusercontent.com/53165464/64251450-340d9600-cf36-11e9-8a83-d6acd534bf4f.PNG)
BUT HERE IT IS SHOWING AS
![NE24](https://user-images.githubusercontent.com/53165464/64251474-425bb200-cf36-11e9-9aae-74ecc4bc9e89.PNG)

**Comment by questglobal-bom** [comment]
Fixed.
