### ISSUE TITLE
HEAT NUMBER IS AUTOMATICALLY SELECTED AS YES EVEN IF IT IS SELECTED AS NO IN AR SCREEN

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#21]
HEAT NUMBER SELECTED AS NO IN AR SCREENS AS NO 
BUT IT DISPLAYED AS NO IN SUMMARY SCREEN
![NE31](https://user-images.githubusercontent.com/53165464/64258230-82c22c80-cf44-11e9-85c5-2e4ae61d1784.PNG)
![NE30](https://user-images.githubusercontent.com/53165464/64258248-8b1a6780-cf44-11e9-9207-dd21e4cb963f.PNG)

**Comment by kumatolemahesh** [comment]
FIXED
