### ISSUE TITLE
GETTING TWO FLANGED SLEEVES FOR SF3550

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#23]
INPUTS ARE
![555](https://user-images.githubusercontent.com/53165464/64329230-88734d00-cfec-11e9-847c-bf1e4ac24482.PNG)
OUTPUT IS 
[OUTPUT OF 4.xlsx](https://github.com/questglobal-bom/bom-configurator-v1/files/3578474/OUTPUT.OF.4.xlsx)
ACTUAL OUTPUT 
![Test_Result4](https://user-images.githubusercontent.com/53165464/64329557-18b19200-cfed-11e9-9006-3594bd6d532d.JPG)

**Comment by questglobal-bom** [comment]
Fixed
