### ISSUE TITLE
ONE EXTRA COATING HAS PRESENT IN PAGE 3 OF FLOATER AFTER UPDATING 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#24]
COATING 
SPECIAL HOUSING LENGTH 
AGAIN COATING
![EE1](https://user-images.githubusercontent.com/53165464/64342416-11e44880-d008-11e9-8e9a-0aa1187c279a.PNG)

**Comment by kumatolemahesh** [comment]
Removed Extra coating and it is fixed
