### ISSUE TITLE
IN AR MODULE FOR GAS HANDLERS SERIES IS NOT DISPLAYING VALUES 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#27]
DUE TO SERIES HOUSING NUMBER ,STAGEFLOW,BEARING RATIOS IS NULL 
![EE3](https://user-images.githubusercontent.com/53165464/64407724-af8c5600-d0a2-11e9-8487-213e211fee83.PNG)
![EE4](https://user-images.githubusercontent.com/53165464/64407735-b4e9a080-d0a2-11e9-9697-b8052e32e1cb.PNG)

**Comment by kumatolemahesh** [comment]
FIXED
