### ISSUE TITLE
CHANGE IN SLB RETROFIT TO BE UPDATED

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#3]
1. FOR RETROFITTING SLB/REDA  RETROFIT IS NOT ON THE SAME LINE 

![NE2](https://user-images.githubusercontent.com/53165464/64148964-4efede00-ce42-11e9-9841-ef92716ac1bf.PNG)

**Comment by kumatolemahesh** [comment]
FIXED
