### ISSUE TITLE
FOR SFGH 2500 AR MODULE OF 2:1 IN THE OUTPUT IMPELLER IS MISSING 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#30]
ACTUAL OUTPUT 
![Test_Result2](https://user-images.githubusercontent.com/53165464/64427980-2855d700-d0d0-11e9-8b70-e48d76b0efaa.JPG)

BUT THE OUTPUT IS 
![ee6](https://user-images.githubusercontent.com/53165464/64428000-3b68a700-d0d0-11e9-9ce6-7b49dad65d21.PNG)

**Comment by prathika123** [comment]
![EE7](https://user-images.githubusercontent.com/53165464/64428346-23455780-d0d1-11e9-92fa-36e9229ee5d4.PNG)

**Comment by questglobal-bom** [comment]
Fixed.
