### ISSUE TITLE
AR MODULE SCREEN 2 NEXT BUTTON IS NOT DISABLED 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#31]
IN AR 2 AND 3 SCREENS  THE NEXT BUTTON IS ENABLED WITHOUT SELECTING SHAFT MATERIAL ,RETROFIT NEXT BUTTON IS ENABLED 
![EE9](https://user-images.githubusercontent.com/53165464/64506540-8dd6dd00-d2f5-11e9-8332-43bdf5d7dde1.PNG)
![EE10](https://user-images.githubusercontent.com/53165464/64506549-93342780-d2f5-11e9-9bbd-65e2c0adf0ed.PNG)

**Comment by prathika123** [comment]
SAME PROBLEM FOR FLOATERS AND COMPRESSION SCREENS

**Comment by kumatolemahesh** [comment]
Now disabling and it is fixed
