### ISSUE TITLE
HOUSING OD AND GENERATE BOM BUTTON IS NOT WORKING 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#32]
HOUSING OD IS SELECTED AS DEFAULT BUT IT SHOWING AS NULL 
![EE11](https://user-images.githubusercontent.com/53165464/64521239-4a8c6680-d315-11e9-953b-ca1d4bc46a2b.PNG)

**Comment by kumatolemahesh** [comment]
fixed
