### ISSUE TITLE
CHANGE TO BE UPDATED IN SUMMARY SCREEN

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#4]
IN SUMMARY SCREEN TYPE OF FLOW=mixed ,THIS SHOULD BE IN CAPITALS OR MAKE ATLEAST FIRST LETTER AS CAPITAL Mixed or MIXED
![NE5](https://user-images.githubusercontent.com/53165464/64149078-a43aef80-ce42-11e9-86eb-975eaa21056c.PNG)

**Comment by kumatolemahesh** [comment]
FIXED
