### ISSUE TITLE
 IT SHOULD DISPLAY AS RATIO OF BEARING TO NON BEARING STAGE 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#44]
![EE23](https://user-images.githubusercontent.com/53165464/64853213-93eff500-d638-11e9-9ced-76a19716a0cf.PNG)
IN SUMMARY SCREEN IT IS DISPLAYING CORRECTLY 
![EE24](https://user-images.githubusercontent.com/53165464/64853278-b71aa480-d638-11e9-8713-6eb0e2f4c308.PNG)

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
verified and closed
