### ISSUE TITLE
GENERATE Bom buttons are not working in compression type of  pump 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#50]
in frontend  response is coming but through backend it is not coming 
![res11](https://user-images.githubusercontent.com/53165464/64934924-7c4c8280-d86b-11e9-9f85-a53d27d171bc.PNG)

**Comment by kumatolemahesh** [comment]
FIXED

**Comment by prathika123** [comment]
verified and closed
