### ISSUE TITLE
IN NON-AR AND FLOATER  FONT DIFFERENCE 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#51]
![FONT](https://user-images.githubusercontent.com/53165464/64954426-2b588080-d8a3-11e9-8f88-c3368df112e2.PNG)
 THERE IS DIFFERENCE BETWEEN  HEAD AND BASE MATERIAL FONT AND HEAD AND BASE OD FONT

**Comment by kumatolemahesh** [comment]
Fixed
