### ISSUE TITLE
Persistent issue at retrofitting 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#52]
![retro](https://user-images.githubusercontent.com/53165464/64955791-c56df800-d8a6-11e9-97a9-d0c1735cf7e0.PNG)

**Comment by prathika123** [comment]
![type](https://user-images.githubusercontent.com/53165464/64955930-1da4fa00-d8a7-11e9-816a-fa3d77fe19b7.PNG)

**Comment by kumatolemahesh** [comment]
Fixed

**Comment by prathika123** [comment]
I CAN STILL SEE THIS ERROR

**Comment by kumatolemahesh** [comment]
Fixed

**Comment by prathika123** [comment]
verified and closed
