### ISSUE TITLE
Spacing is not same in retrofitting,overlap stage design

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#54]
![ret](https://user-images.githubusercontent.com/53165464/65240595-41627d00-daff-11e9-9ac6-a5fa336d1ff0.PNG)

**Comment by prathika123** [comment]
![over](https://user-images.githubusercontent.com/53165464/65240902-f09f5400-daff-11e9-91c5-82eb8e44bc6d.PNG)

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
verified and closed
