### ISSUE TITLE
ACTUALLY IN AR MODULE OF GAS HANDLERS SFGH2500 2:1 THERE SHOULD NOT BE ANY AR STAND OFF SLEEVE BUT IT IS DISPLAYING  AR SLEEVE QUANTITY

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#56]
![SNIP 1](https://user-images.githubusercontent.com/53165464/65242605-0f074e80-db04-11e9-8373-6d5dbe0cff3f.PNG)
![SNIP2](https://user-images.githubusercontent.com/53165464/65242621-19c1e380-db04-11e9-960d-13ca9e900f36.PNG)

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
VERIFIED AND CLOSED
