### ISSUE TITLE
Same in case of 1:1 or 2:1 ar stand off sleeve should not be present 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#57]
![SNIP3](https://user-images.githubusercontent.com/53165464/65243683-6c9c9a80-db06-11e9-8327-10de2c478898.PNG)
![SNIP4](https://user-images.githubusercontent.com/53165464/65243694-745c3f00-db06-11e9-9e8b-b37c78b10e02.PNG)

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
VERIFIED AND CLOSED
