### ISSUE TITLE
Based on the inputs given for intake shaft material,hex nut should be present but the description is empty  

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#62]
![intake 1](https://user-images.githubusercontent.com/53165464/65490007-f6af7f00-dec9-11e9-9a2c-ad7c2976294e.PNG)
![intake 2](https://user-images.githubusercontent.com/53165464/65490095-23639680-deca-11e9-88ff-0f62ff5facfc.PNG)

**Comment by questglobal-bom** [comment]
Fixed.

**Comment by prathika123** [comment]
Still i could nt find shaft description

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
verified and closed
