### ISSUE TITLE
With the same inputs in intake  there should be 2 shipping caps but there is only 1 shipping cap 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#63]
![intake 2](https://user-images.githubusercontent.com/53165464/65490193-527a0800-deca-11e9-821c-1499adb914bf.PNG)
based on shipping cap with same part number,there should be 2 shipping caps
![in 3](https://user-images.githubusercontent.com/53165464/65490267-776e7b00-deca-11e9-99e0-6b8814cd6903.PNG)

**Comment by questglobal-bom** [comment]
If the part numbers are same for both shipping cap entries, then we display only one entry with quantity 2. Hence marking this issue as invalid.
