### ISSUE TITLE
Both clocked and default should be present 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#66]
![ge5](https://user-images.githubusercontent.com/53165464/65665706-cdbdf400-e059-11e9-8fc9-b022608fc2ad.PNG)

**Comment by questglobal-bom** [comment]
CLOCKED must be present along with DEFAULT. Do not replace CLOCKED with DEFAULT.

**Comment by kumatolemahesh** [comment]
Fixed

**Comment by prathika123** [comment]
verified and closed
