### ISSUE TITLE
There is no housing and shaft description present in gas separator  of standard flow 400 series 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#68]
![ge 6](https://user-images.githubusercontent.com/53165464/65670010-2b563e80-e062-11e9-8e77-669ee099eaad.PNG)
![ge 7](https://user-images.githubusercontent.com/53165464/65670031-3315e300-e062-11e9-8a43-61450a0c3c8d.PNG)

**Comment by questglobal-bom** [comment]
Fixed.

**Comment by prathika123** [comment]
verified and closed
