### ISSUE TITLE
VALUES FOR STAGEFLOW OF GAS HANDLERS IS NOT DISPLAYING PROPERLY

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#7]
VALUES OF SF=SFGH2500,SFGH7000
IT IS DISPLAYED AS SFG250,SFG700 ONLY AFTER DRAGGING DROPDOWN IT IS SHOWING EXACT VALUES 
![NE7](https://user-images.githubusercontent.com/53165464/64154826-3648f500-ce4f-11e9-89e2-0153c4815676.PNG)

**Comment by kumatolemahesh** [comment]
FIXED
