### ISSUE TITLE
All the particular fields which are present in orange colour should be present only in high flow but these are present in standard flow  

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#70]
![ge8](https://user-images.githubusercontent.com/53165464/65670497-19c16680-e063-11e9-9876-4f6d6cb9a38b.PNG)
![ge9](https://user-images.githubusercontent.com/53165464/65670511-204fde00-e063-11e9-9b54-3c7b8bbe8b01.PNG)
![ge10](https://user-images.githubusercontent.com/53165464/65670521-2645bf00-e063-11e9-9e67-a1efea0a79e5.PNG)
![ge 6](https://user-images.githubusercontent.com/53165464/65670537-31005400-e063-11e9-81e7-a6e40da45275.PNG)
![ge 7](https://user-images.githubusercontent.com/53165464/65670551-35c50800-e063-11e9-8970-67758d00414c.PNG)

**Comment by questglobal-bom** [comment]
Fixed.

**Comment by prathika123** [comment]
verified and closed
