### ISSUE TITLE
There is no spacer sleeve present in the pdf  and in first line of pdf it is showing as gas separator high flow  even it is selected as standard flow

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#71]
![ge10](https://user-images.githubusercontent.com/53165464/65670726-905e6400-e063-11e9-897e-638d37b953c2.PNG)
![ge11](https://user-images.githubusercontent.com/53165464/65670733-96544500-e063-11e9-83f4-835b251244b0.PNG)
![ge 6](https://user-images.githubusercontent.com/53165464/65670747-9bb18f80-e063-11e9-96b6-7ab17ac6950b.PNG)

**Comment by prathika123** [comment]
i still dont find spacer sleeve

**Comment by questglobal-bom** [comment]
Fixed.
