### ISSUE TITLE
There is no Base Plug present for the given inputs 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#76]
![ve1](https://user-images.githubusercontent.com/53165464/66205396-efa71e80-e6ca-11e9-8644-e38a33e6dce1.PNG)
But for given inputs base plug should be present 
![ve2](https://user-images.githubusercontent.com/53165464/66205461-17968200-e6cb-11e9-8560-91caaf803dc9.PNG)

**Comment by questglobal-bom** [comment]
Fixed.

**Comment by prathika123** [comment]
verified and closed
