### ISSUE TITLE
Shaft should not be present for given inputs

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#77]
![ve1](https://user-images.githubusercontent.com/53165464/66205528-401e7c00-e6cb-11e9-8a19-d363c9e609ad.PNG)
Based on the table it should not be present 
![ve3](https://user-images.githubusercontent.com/53165464/66205602-6c39fd00-e6cb-11e9-8a84-b558c5220566.PNG)

**Comment by questglobal-bom** [comment]
![image](https://user-images.githubusercontent.com/53071398/66205856-1d409780-e6cc-11e9-8ba2-ffaae844159d.png)

**Comment by questglobal-bom** [comment]
Shaft entry will be present as seen in the attached image.
