### ISSUE TITLE
Quantity of female connector is varying, it should be 3 always for all the cases

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#78]
![fc1](https://user-images.githubusercontent.com/53165464/66286957-56a61c80-e8f1-11e9-9034-02a05bc20f4c.PNG)
![fc2](https://user-images.githubusercontent.com/53165464/66286964-5c036700-e8f1-11e9-9f6c-bd967f02aad9.PNG)

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
Verified and Closed
