### ISSUE TITLE
There are 2 heads present in the output of gas separator 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#80]
![image](https://user-images.githubusercontent.com/53165464/66301519-e90be780-e914-11e9-8d02-6512a30c3886.png)
![image](https://user-images.githubusercontent.com/53165464/66301584-06d94c80-e915-11e9-9895-136b4ce3bae0.png)

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
Verified and Closed
