### ISSUE TITLE
There are some spelling corrections please correct it 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#82]
![image](https://user-images.githubusercontent.com/53165464/66539137-b34d4580-eb44-11e9-95bf-b6a9a47ce414.png)
![image](https://user-images.githubusercontent.com/53165464/66539269-14751900-eb45-11e9-8372-b1a347adfc10.png)
please correct font style in bold and correct spellings as backstock material=bar stock material,shaft material,bag material

**Comment by kumatolemahesh** [comment]
Fixed

**Comment by prathika123** [comment]
![image](https://user-images.githubusercontent.com/53165464/66570135-950a3880-eb8a-11e9-9e1d-d3ffb96219d8.png)

**Comment by prathika123** [comment]
Verified and closed
