### ISSUE TITLE
Base  description is not present in output  for the given input 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#84]
![image](https://user-images.githubusercontent.com/53165464/66559559-371e2680-eb73-11e9-9b91-0685ff6e3333.png)
![image](https://user-images.githubusercontent.com/53165464/66559597-44d3ac00-eb73-11e9-8040-53aa1aeda900.png)

**Comment by questglobal-bom** [comment]
Fixed

**Comment by prathika123** [comment]
Verified and Closed
