### ISSUE TITLE
VALUES FOR STAGEFLOW OF GAS HANDLERS IS NOT DISPLAYING PROPERLY FOR 513 SERIES

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#9]
SF=SFGH7000
IT IS DISPLAYED AS SFGH700
![NE9](https://user-images.githubusercontent.com/53165464/64158945-01d93700-ce57-11e9-84e6-ab63b7561127.PNG)

**Comment by questglobal-bom** [comment]
513 Series is not in current scope.
