### ISSUE TITLE
Head and Base entries are missing for given inputs 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#92]
![image](https://user-images.githubusercontent.com/53165464/67002459-9511b780-f0f9-11e9-8fd5-a51589725465.png)
![image](https://user-images.githubusercontent.com/53165464/67002477-9fcc4c80-f0f9-11e9-8f96-57dcee788433.png)

**Comment by questglobal-bom** [comment]
Fixed for Head entry.
Base entry will not be present as there is no part present in database for the selected inputs.

**Comment by prathika123** [comment]
ok
VERIFIED AND CLOSED
