### ISSUE TITLE
Centralizer and shaft are missing for the inputs

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#94]
![image](https://user-images.githubusercontent.com/53165464/67177280-82de9480-f3eb-11e9-9f1b-519ef46b20c5.png)
![image](https://user-images.githubusercontent.com/53165464/67177291-8c67fc80-f3eb-11e9-8696-84a4c486da36.png)

**Comment by questglobal-bom** [comment]
Fixed.

**Comment by prathika123** [comment]
shaft is still missing

**Comment by prathika123** [comment]
Verified and Closed
