### ISSUE TITLE
AR diffuser description is missing in AR of SF1750 

### ISSUE THREAD

**Issue by prathika123** [questglobal-bom/bom-configurator-v1#98]
![image](https://user-images.githubusercontent.com/53165464/68111876-25336780-ff16-11e9-8244-8fe5e1271aca.png)
![image](https://user-images.githubusercontent.com/53165464/68111993-61ff5e80-ff16-11e9-8e69-466213dc8006.png)

**Comment by questglobal-bom** [comment]
Fixed.

**Comment by prathika123** [comment]
VERIFIED AND CLOSED
